apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: AccuWeather
  description: Accurate Weather App - This App provides accurate weather information
  tags:
    - weather-app
  annotations:
   "backstage.io/kubernetes-label-selector": "app.kubernetes.io/part-of=accuweather"
spec:
  type: service
  lifecycle: prototype
  owner: default-team